[workspace]
authors = ["Brylie Christopher Oxley <brylie@protonmail.com>"]
channels = ["conda-forge"]
name = "calyx"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[dependencies]
quarto = "1.8.27.*"
python = ">=3.11"
jupyter = "*"
ipykernel = "*"

[tasks]
docs = "quarto render"
preview = "quarto preview"
